image:
  file: ./.gitpod.Dockerfile
ports:
- port: 5432
  onOpen: ignore
- port: 3000
  onOpen: ignore

tasks:
- name: Redis
  command: redis-server
- name: Setup
  init: >
    psql -h localhost -d postgres --file=support/setup_postgres.sql &&
    npm i
  command: npm run start